### PR TITLE
Edward's task

### PR DESCRIPTION
**Pull request by Edward-Inaction**
Hey,

**QR Generator** and **Gradle Tools Test** is finished in this PR.

### CODE REVIEW

**Comment by kuno** [comment]
Hi @Edward-Inaction 

I am trying to build you app on Android Studio 3.0.0 beta2, I always get `Error: Connection refused`.

Can you try to resolve this issue ?

seedadapter_kt_-_qrgenerator_-____works_androidstudioprojects_test-mobile_qr-generator_qrgenerator__-_android_studio_3_0_beta_2

**Comment by kuno** [comment]
@Edward-Inaction 

I try to build you app, but the python server failed to handle request

```python
Traceback (most recent call last):
  File "/Users/kuno/.pyenv/versions/3.5.3/lib/python3.5/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Users/kuno/.pyenv/versions/3.5.3/lib/python3.5/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "server.py", line 10, in seed
    'data': get_seed(),
  File "server.py", line 16, in get_seed
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=32))
AttributeError: module 'random' has no attribute 'choices'
127.0.0.1 - - [12/Aug/2017 18:55:49] "GET /api/seed HTTP/1.1" 500 749
```

Please take a look and try to fix it.

On the other hand, for app code,  please remove all the settings that specific to your development environment(eg. proxy settings). To make review easier.

**Comment by Edward-Inaction** [comment]
@kuno 
Sorry about the proxy settings, I forgot to delete them when committing. 

About the Python issue, please use Python 3.6, `random.choices` only exists after 3.6. Sorry I didn't write this into documentation, changing it now.

**Comment by kuno** [comment]
@Edward-Inaction 

I've tried the code, and it works.

The only thing I need to change is that the server IP, so it can work my devices and network.

**Pull request closed without merging**
