### PR TITLE
Create MobileTest Application

### PR DESCRIPTION
**Pull request by kafka0000**
feat: feat(github test app): create application

docs：Design.md(see the project)

### CODE REVIEW

**Comment by jhonny-me** [comment]
@kafka0000 Hi, we are not able to identify who you are, can you send us an email or comment here?

**Comment by kafka0000** [comment]
Hi. My name is  Yanjun.li.  Heres my E-mail:  kafka673@gmail.com

**Comment by jhonny-me** [comment]
@kafka0000 well received, we'll review and get back to you once we have a decision.

**Comment by jhonny-me** [comment]
Hi, @kafka0000 can you explain why:
- choose class instead of struct for data model
- recurred do catch in UserService
- detail page is managed by user list page instead of coordinator

Also, can you:
- fix the warnings
- fix the force unwrap
- merge UserCell and UserDetailCell
- the detail header looks wired on iphone8

**Comment by kafka0000** [comment]
Received.

Thanks for you reply. Really appreciate your time.

The Reason are as follows：

* Q:  choose class instead of struct for data model
* A:  The struct has two modes: mutable or immutable.if you assign  a struct value to let, the value becomes immutable mode, even calling any mutating method cannot change any State in the value. In this homework ,when i use driver to drive with tableview, the element in callBack is immutable. I think it’s a better way to use class type instead of struct  type to change model’s following state in this case.

* Q: recurred do catch in UserService
* A: The router pattern is an important part of organizing the network layer.A router is a type that defines routes or URLRequest components.In HttpRouter,  the func asUrlRequest() request() may throw, when the service fetch users is called, the error need to be handled.You can see the latest commit that part of code replaced by Result type, it may looks better.

* Q: detail page is managed by user list page instead of coordinator
* A: Hmm, at the end of time closely to finished this homework, I was doubting myself, saying maybe that designed too much with this project. The logic of homework should be more clear, so only the launch logic remains.

In addition to these QA, the other issues have been fixed.

Looking forward to have the opportunity to hopefully work with you !

**Comment by jhonny-me** [comment]
@kafka0000 I think we are able to draft a result, thanks for your reply.

**Pull request closed without merging**
