### PR TITLE
Feature tianxiao

### PR DESCRIPTION
**Pull request by xiaoChannel**
Coding finished, please approve.
 - tianxiao875@126.com

### CODE REVIEW

**Comment by seazon** [comment]
@xiaoChannel will check it tomorrow

**Comment by seazon** [comment]
@xiaoChannel 
- The unit tests don't seem to make much sense.
- androidx.legacy:legacy-support-v4:+
  - This is deprecated.
  - Avoid using + in version numbers; can lead to unpredictable and unrepeatable builds.
- The detail header is not handle well.

**Comment by xiaoChannel** [comment]
· Indeed, unit tests are somewhat pointless to write.
androidx.legacy:legacy-support-v4:+
and + , indeed my oversight.
Thanks for pointing out. I will pay attention to this arrangement in the future.
· Details header. What's wrong with handling? Appreciate further details.
    Is the animation or its shrunken display poorly handled?
   I personally like the concise way, so I think it needs a title, after the swipe to hide, and the list below has enough obvious information, which was my initial thought.

**Comment by jhonny-me** [comment]
@xiaoChannel Thanks for your reply, we've collected enough information for us to proceed.

**Pull request closed without merging**
