### PR TITLE
github_user_list

### PR DESCRIPTION
**Pull request by likainian**
Hi, I have finished this demo，please check:
github_user_list

### CODE REVIEW

**Comment by seazon** [comment]
@likainian seems you submitted a new PR, will check it later.

**Comment by likainian** [comment]
我用注入方式做了实现

**Comment by seazon** [comment]
Checked and I think we have enough info to move on.

**Comment by likainian** [comment]
Thinks for your time. What is next I need to do?



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 12, 2021 13:19 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [Wiredcraft/test-mobile] github_user_list (#48)




 
Checked and I think we have enough info to move on.
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by seazon** [comment]
@likainian will contact you via email.

**Pull request closed without merging**
