### PR TITLE
Feature/square animation

### PR DESCRIPTION
**Pull request by seandeng**
task finished.

iOS version with Swift is in Simple-Animation-iOS folder.
Android version with Kotlin is in Simple-Animation-Android folder.

I have test iOS version on my iPhone. But i have no Android physical device, i can't test it.

Please review it.

### CODE REVIEW

**Comment by makara** [comment]
Thanks @seandeng. We were too busy on JSConf last week. Will get back to you soon.

**Comment by WXGBridgeQ** [comment]
@seandeng 
Hi, we've just reviewed your work.
I saw you used the CoreMotion for the iOS test, I want to know why you choose to use it, have you ever considered other solutions (such as UIDynamic)? What's your opinion about this question?

**Comment by seandeng** [comment]
@WXGBridgeQ ,  thanks for review ,  i have not use UIDynamic before .   

It is a task depend on gravity.
I want to test it in physical device , because physical device have the accurate gravity value , it is used in physical finally.
if i use UIDynamic , it just simulate the animation , not test it accurately.

**Comment by makara** [comment]
Hi @seandeng, one more thing and we should be good to take a decision from there. Can you explain more about how you analyze the requirements? More specifically:

- Why did you say it has to be accurate and not a simulation? What's the benefit?
- What if there are multiple objects and they can collapse? Would you use a different thing or would you mix the technologies?

**Comment by seandeng** [comment]
Becasue in the physical device , CoreMotion will provide you with the correct acceleration and offset when you shake and tilt the iPhone. It will make the animation realistic.

If multiple objects can collapse , it should mix the technologies , use both of CoreMotion and UIDynamic.   UIDynamic have the collisionBehavior.

CoreMotion just keep the  magnitude value realistic.

**Comment by makara** [comment]
Thanks @seandeng this should be enough for us to take a decision. We'll get back to you soon. Closing.

**Pull request closed without merging**
