### PR TITLE
My solution to QR-generator

### PR DESCRIPTION
**Pull request by jludden**
Hi WiredCraft team!

Here's my solution to the QR-generator project. All of my files are in the QR-generator folder, and the documentation is in [QR-generator-solution.md](https://github.com/jludden/test-mobile/blob/master/QR-generator/QR-generator-solution.md). If you want to check it out right away, feel free to demo in a [web browser](https://appetize.io/embed/nwmw280f28cg1cwkgrk9aw2adr?device=nexus5&scale=75&orientation=portrait&osVersion=7.1).

Thanks for your consideration and any feedback is appreciated!

### CODE REVIEW

**Comment by kuno** [comment]
Hi @jludden 

I am the Android development head in wiredcraft now.

Can you convert to code to using databinding and try to implement some dependency injection in you project ?

**Comment by jludden** [comment]
Hi @kuno thanks for the feedback. I'll work on updating the project this weekend!

**Comment by jludden** [comment]
Hi @kuno I'm looking into this again, and I am planning on adding some data binding tomorrow.

Can you go into more detail on what you would like to see with dependency injection though? I am using a simple DI setup to inject a different QRSeedProvider based on the build variant for testing (the two different Injection.kt objects in the prod vs test folders). Would you prefer me to use a third-party like Dagger 2 instead? Any tips would be appreciated! Thanks!

**Comment by kuno** [comment]
@jludden 
dagger 2 is a good choice, nothing fancy here just show us you dagger/di knowledge

**Comment by jludden** [comment]
@kuno updated - let me know if you have any questions about my implementation. Thanks for your feedback so far!

**Comment by jludden** [comment]
Vv by a

**Pull request closed without merging**
