### PR TITLE
Sam's work.

### PR DESCRIPTION
**Pull request by simpzan**
I just started to work on the task. 
Firstly I made a little fake node.js server with 2 commits.

PS: I fixed some typos :)

### CODE REVIEW

**Comment by simpzan** [comment]
@makara I got some new questions. 
1. Does the server need to persist generated history seeds to db?  I found the following requirements. 
'Choose either sql or no-sql database to make the data persistence;'
2. Regarding validate server api, what is valid seed? Is a expired history seed valid?
3. My mac is 10.10.5 which does not support swift 2.2. My currently installed Xcode only include swift 2.0 compiler, so my current codebase is swift 2.0. Is it acceptable, or I have to update to 2.2?

**Comment by simpzan** [comment]
Another question. Need I consider system time mismatch between server and client?

**Comment by simpzan** [comment]
is anybody here can answer my questions?

**Comment by makara** [comment]
Before I answer the questions, can you tell us what do you think? For example do you see it useful to persist the seeds? How would you tell a generated code is valid?

**Comment by simpzan** [comment]
OK. 
1, for seed persistance. I think persist the latest seed is enough for server restart recovery, in which case a simple json file is enough, db is not needed. I don't see it useful to persist history seeds.
2, for valid seed, I think the expired seed is invalid. only non-expired matched current seed is valid. It is my current implementation.
3, regarding swift, I just wonders if you guys have swift 2.0 installed, if yes, I think swift 2.0 code is ok for review. it not, I will definitely upgrade my dev environment to adapt my code to swift 2.2. For long term projects, we definitely need to upgrade our dev environment to keep up with the development of the platform.
4, for mismatched system time issue, I just don't see it an issue initially,  I thought most devices is synchronized with the help of NTP. But when I am test the app on my iphone with server on my mac, I found that there's 6s mismatch, though both devices are set to set system time automatically. So I think it is needed to consider the issue.

**Comment by makara** [comment]
I agree with all your points. Regarding to the time difference thing, I think it's the problem of the design itself, and I don't think it can be solved without changing the plan completely. What do you think?

Also let me know when your PR is ready for review.

**Comment by simpzan** [comment]
I just learned a little about NTP protocol. I found the basic algorithm behind NTP is really simple, https://en.wikipedia.org/wiki/Network_Time_Protocol#Clock_synchronization_algorithm 
I think I can make a simple implementation on top of the existing /seed http api and swift http client to get the time difference between server and client, and then convert the seed expire time to client system time using the time difference.

**Comment by makara** [comment]
@simpzan Sounds great, but don't over engineer it for now. Please let us know once you feel comfortable for a review.

**Comment by simpzan** [comment]
Thanks for the advice. I will ignore the time diff issue for now. 

The main logic is all working now, There's some ui/ux tweaks and doc need to be done. 
I will let you know when I am finished and ready for review.

**Comment by simpzan** [comment]
@makara I am ready for review, finally! 

PS: I found the home ui in the mockup is using the speed dial type of Floating Action Button of Google Material Design. Since I am developing an iOS app, instead I implemented a simple navigation bar button ui. 
simulator screen shot aug 1 2016 8 11 26 pm

**Comment by makara** [comment]
Thanks. We'll get back to you soon.

**Pull request closed without merging**
