### PR TITLE
The QRGenerator iOS app is ready for review

### PR DESCRIPTION
**Pull request by ryantbd**
Hi @makara, I've just finished the task which you assigned to me last week. I've completed most of the following requirements and I think this fork is ready for code review. Thanks!
- [x] Build a simple API server that can provide an endpoint which generates a random seed
- [x] Build a simple mobile application (very simple UI), that would call the seed API and generate a QR-code based on this seed
- [x] QR-code could automatically refresh based on an expired date provide by the seed API
- [x] Mobile devices should cache the seed data and the seed can be restored after the user force close the app
- [x] Follow the User Interface draft
- [x] Backend with Loopback
- [x] Mobile app with React Native
- [x] Documentation
- [ ] Follow Apple / Google design pattern (not sure)
- [ ] Proper unit test (partial)
- [x] Choose either SQL or noSQL database to make the data persistence (PostgreSQL)
- [x] Use git to manage code

### CODE REVIEW

**Comment by makara** [comment]
Thanks. We'll get back to you soon.

cc @wwayne @xeodou @WXGBridgeQ .

**Comment by ryantbd** [comment]
Thanks, I've just make the API server running on my VPS. Now you can set the environment variable `API_HOST` to `http://qrgenerator-api.ryan.host` to make this review work more easier :D

**Comment by makara** [comment]
Quick question @ryaneof :
- Why did you use your forks for some of the npm modules? If you fixed something would you send the fix back to the modules?

**Comment by ryantbd** [comment]
Hi @makara I've used fork of `ex-navigator` and `react-native-qrcode`. In short, they both have some compatibility issue with React Native v0.19. Someone has sent back the issue to `ex-navigator`, they haven't fixed this yet. As for `react-native-qrcode`, it has not been updated for a while, I'll submit an issue with this fix later.

**Comment by makara** [comment]
@ryaneof Thanks for your time. We'll get back to you soon. I'm closing this for now. Please feel free to play with it or contact us anytime.

**Comment by ryantbd** [comment]
@makara Thanks, looking forward to hearing from you :)

**Pull request closed without merging**
