### PR TITLE
PR for QR generator test

### PR DESCRIPTION
**Pull request by seazon**

### CODE REVIEW

**Comment by makara** [comment]
Hey @seazon, thanks for the PR.

I see you have a few commits about the "Advanced requirements". Could you describe more about the strategies in your document, such as, how you understand the requirements, what the flow is, how you structure it etc? Bear in mind that a "strategy" means a lot more than just a piece of code.

**Comment by seazon** [comment]
I updated my document. https://github.com/seazon/test-mobile/blob/master/QRGenerator/doc/reedme.md

**Comment by seazon** [comment]
Hi @makara, I have updated my document.

**Comment by makara** [comment]
Thanks @seazon. I think we have enough info to move on. We'll get back to you soon. Closing.

**Comment by seazon** [comment]
Thanks @makara .

**Pull request closed without merging**
